eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.137:8761/eureka/
      
server:
  port: 8765

feign: 
  hystrix:
    enabled: true
spring:
  application:
    name: eshop-datasync-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.1.140:3306/eshop?characterEncoding=utf8
    username: eshop
    password: eshop
  rabbitmq:
    host: 192.168.1.137
    port: 5672  
    username: rabbitadmin  
    password: 123456